#!/bin/bash

cat <<EOF >~/.local/share/applications/discord.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Discord (Web)
Comment=Launch Discord
Exec=launch-webapp https://discord.com/channels/@me"
Icon=$HOME/.local/share/applications/icons/Discord.png
Terminal=false
StartupNotify=true
EOF
